### ISSUE TITLE
Remove your login credentials from appsettings.json!

### ISSUE THREAD

**Issue by gh9st33** [DiegoLins10/PinguCheckIn#1]
Just a heads up - you shared your working (i tested it)  login information to your database (which matches your github password... I checked that too). I suggest working with only local databases in the development level, this way you  dont share your credentials, or at least use something like "DevUser - DevPass123" for your development cycle. Don't worry, I didn't actually login to you accounts, but I got to the 2FA screen. Just trying to inform you! Good Luck!

**Comment by DiegoLins10** [comment]
Oh sure, Thanks for help me. It was a college work. Next days this database will be delete but thanks for it ;)
